"""empty message

Revision ID: 0bfce2f30439
Revises: b24b7eaf2768
Create Date: 2024-09-28 15:41:23.485454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfce2f30439'
down_revision = 'b24b7eaf2768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recorded_contact_audit', sa.Column('audit_start_date', sa.DateTime(), nullable=True))
    op.add_column('recorded_contact_audit', sa.Column('audit_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recorded_contact_audit', 'audit_end_date')
    op.drop_column('recorded_contact_audit', 'audit_start_date')
    # ### end Alembic commands ###
