"""empty message

Revision ID: b24b7eaf2768
Revises: 9eeb11f04482
Create Date: 2024-09-26 16:46:20.516488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b24b7eaf2768'
down_revision = '9eeb11f04482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recorded_contact_audit',
    sa.Column('recorded_contact_id', sa.Integer(), nullable=False),
    sa.Column('audit_notes', sa.String(length=256), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('audit_type', postgresql.ENUM('COMPETENCY_REVIEW', 'OPERATION_CLOSE_CALL', 'INCIDENT_ACCIDENT', 'ASSURANCE', name='audit_type'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inserted', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['recorded_contact_id'], ['recorded_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recorded_contact_audit')
    # ### end Alembic commands ###
